-- Insert para CGA_META_TABLAS_SGA

-- SGACAC
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAC_DAMBITOSORGS','SGACAC');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAC_DPERFILES','SGACAC');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAC_DUSUARIOS','SGACAC');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAC_PCATAPLIS','SGACAC');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAC_PGRUPOSAMBORG','SGACAC');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAC_PTIPOSAMBORG','SGACAC');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAC_RAPL_USR','SGACAC');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAC_RPRF_USR','SGACAC');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAC_RUSR_AOG','SGACAC');

-- SGACAP
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_DACP_GANADERAS','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_DANI_PAST_EXT','SGACAP'); 
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_DAPROVECHA','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_DAUTORIZA_EC','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_DCENSOEXP','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_DCOBER','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_DDATOS_FISCALES','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_DDERECHOSPB','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_DDET_ENT_ASO','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_DENT_ASO','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_DEXPLOTGAN','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_DEXP_ORI_ANI','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_DINF_ENT_ASO','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_DPASTOSCOMUN','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_DPRD_EST','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_DREC_ADICIONALES','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_DRECINTO','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_DRESP_JUR_EXP','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_DRESUMEN_BCE','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_DSOCIOS','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_DSOLAPE_EP','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_DSOLAPE_FR','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_DSOLICITUD','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_F_OBT_PARAMETRO_INST','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_PCL_VALIDACION','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_PESTADOSOL','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_PTPRELACIONVAL','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_PTPVALIDACION','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_PVALIDACION','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_RCTS_VLD_INC','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_RDAR_RVG','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_RDRA_LTS','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_RPCO_RSP','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_RPDR_SOL_LTS','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_RRAS_IAS','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_RREC_ASC','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_RREC_EXG','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_RREC_LTS','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_RREC_LTS_PDR','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_RREC_PRD','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_RREC_VRD','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_RSOL_DCS','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_RSOL_DCS_CHECK','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_RSOL_ORGPROF','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_RSOL_SAU','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_RSOL_SCS','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_RSOL_VLD','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_RSOL_VLD_DIF_VLD','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_RSOL_VLD_RST','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_RUDS_UIV','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_RUIF_VLD','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_RUIS_UDS','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_RUIS_UIV','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_VCTS_VLD','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_VCTS_VLD_SEL','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_VRESULT_VLD','SGACAP');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAP_VSOL_LNA','SGACAP');

-- SGAGST
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('CAD_RCTR_CAM','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('COM_PCAMPANA','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('COM_PCCAA','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('COM_PMUNICIPIOS','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('COM_PPROVINCIAS','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('COM_PREGMATRIMONIOS','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('COM_PSIGPAC','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('DPE_DCTAS_BANCO','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('DPE_DDATPERSONALES','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('DPE_DDIRECCIONES','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GAS_DRECINTO','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GAS_DREC_AREAS_FOTO','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GAS_PSIGPAC_INC','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_DALEGSU','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_DEXPEPASTO','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_DFOTOPROCESA_PVF','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_DPASTOSCOMUN','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_DORGPROF','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_DRECINTO','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_DRECINTO_APAR','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_DRECINTO_RGP','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_DREC_AREAS_FOTO','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_DSOLICITUD','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PAUTORIZA','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PCTGUGM','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PDESTINO_PROD','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PDOCUMENTO','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PESPECIE','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PESTADOSGESADM','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PFORMAJURIDICA','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PFORMAPERTE_OIA','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PLINEAAYUDA','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PMANTCOBER_SUELO','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PMOTIVOALEGSU','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PORIGENDERECHOPB','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PPCT_JND_ANUAL','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PPRODUCTO','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PRESTOVEGETAL','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PSENP','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PSISEXPLOTER','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PSISPROD_OLIVAR','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PSISTCONDUCCION','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PSISTEMA_CULTIVO','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PSISTEMA_RIEGO','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PSOLICITA','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PTP_FORM_AGR','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PTPACTIVIDADAGR','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PTPALEGASP','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PTPCOBER_SUELO','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PTPCULTIVO_BCE','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PTPEXPLOTGAN','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PTPRACTICA_BCE','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PTPREGTENENCIA','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PTPSEMILLA','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PTPSOLICITUD','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_PVARIEDAD','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_RASU_DOC','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_RCAM_LNA','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_RCAM_TSO','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_RCUL_PRD','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_RPCO_RSP','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GST_VFOTO_LDG','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('MON_RRMN_ZONAREQ','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('REX_PDENORIGEN','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('REX_PINGEOPROT','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('REX_PTPAPROVECHAMIENTOS','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('SGD_DDOCUMENTOS','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('SGD_DEXPEDIENTES','SGAGST');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('SGD_REXP_DOC','SGAGST');

-- SGAGEN
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GEN_CONFIGURACION','SGAGEN');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GEN_DCOMPONENTESINS','SGAGEN');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GEN_DNOMFICHEROS','SGAGEN');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GEN_DPARAMETROSINS','SGAGEN');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GEN_DPARAMETROSPUB','SGAGEN');
INSERT INTO CGA_META_TABLAS_SGA (TX_NOMBRE, TX_GRUPO_SGA) VALUES ('GEN_PACCESOCOMPFICHERO','SGAGEN');


-- CGA_META_ENTREGAS
INSERT INTO CGA_META_ENTREGAS (TX_FICHERO,TX_FECHA,LG_TRATADO,NU_VERSION)
VALUES ('Entrega951-p01.zip',TO_DATE ('01/06/2023 7:25', 'DD/MM/YYYY HH24:MI'), 'S', '951_p01');

INSERT INTO CGA_META_ENTREGAS (TX_FICHERO,TX_FECHA,LG_TRATADO,NU_VERSION)
VALUES ('Entrega951-p02.zip',TO_DATE ('12/06/2023 13:34', 'DD/MM/YYYY HH24:MI'), 'S', '951-p02');

INSERT INTO CGA_META_ENTREGAS (TX_FICHERO,TX_FECHA,LG_TRATADO,NU_VERSION)
VALUES ('VERSION_960.zip',TO_DATE ('15/06/2023 16:30', 'DD/MM/YYYY HH24:MI'), 'S', '960');

INSERT INTO CGA_META_ENTREGAS (TX_FICHERO,TX_FECHA,LG_TRATADO,NU_VERSION)
VALUES ('Entrega960-p01.zip',TO_DATE ('20/06/2023 14:06', 'DD/MM/YYYY HH24:MI'), 'S', '960-p01');

INSERT INTO CGA_META_ENTREGAS (TX_FICHERO,TX_FECHA,LG_TRATADO,NU_VERSION)
VALUES ('Entrega960-p02.zip',TO_DATE ('26/06/2023 13:59', 'DD/MM/YYYY HH24:MI'), 'S', '960-p02');

INSERT INTO CGA_META_ENTREGAS (TX_FICHERO,TX_FECHA,LG_TRATADO,NU_VERSION)
VALUES ('VERSION_961.zip',TO_DATE ('29/06/2023 20:01', 'DD/MM/YYYY HH24:MI'), 'S', '961');

INSERT INTO CGA_META_ENTREGAS (TX_FICHERO,TX_FECHA,LG_TRATADO,NU_VERSION)
VALUES ('Entrega961-p01.zip',TO_DATE ('03/07/2023 7:52', 'DD/MM/YYYY HH24:MI'), 'S', '961-p01');

INSERT INTO CGA_META_ENTREGAS (TX_FICHERO,TX_FECHA,LG_TRATADO,NU_VERSION)
VALUES ('Entrega961-p02.zip',TO_DATE ('05/07/2023 13:54', 'DD/MM/YYYY HH24:MI'), 'S', '961-p02');

INSERT INTO CGA_META_ENTREGAS (TX_FICHERO,TX_FECHA,LG_TRATADO,NU_VERSION)
VALUES ('VERSION_970.zip',TO_DATE ('13/07/2023 19:38', 'DD/MM/YYYY HH24:MI'), 'S', '970');

INSERT INTO CGA_META_ENTREGAS (TX_FICHERO,TX_FECHA,LG_TRATADO,NU_VERSION)
VALUES ('Entrega970-p01.zip',TO_DATE ('20/07/2023 12:50', 'DD/MM/YYYY HH24:MI'), 'S', '970-p01');

INSERT INTO CGA_META_ENTREGAS (TX_FICHERO,TX_FECHA,LG_TRATADO,NU_VERSION)
VALUES ('Entrega970-p02.zip',TO_DATE ('28/07/2023 12:59', 'DD/MM/YYYY HH24:MI'), 'S', '970-p02');

INSERT INTO CGA_META_ENTREGAS (TX_FICHERO,TX_FECHA,LG_TRATADO,NU_VERSION)
VALUES ('VERSION_971.zip',TO_DATE ('03/08/2023 19:39', 'DD/MM/YYYY HH24:MI'), 'S', '971');

INSERT INTO CGA_META_ENTREGAS (TX_FICHERO,TX_FECHA,LG_TRATADO,NU_VERSION)
VALUES ('VERSION_980.zip',TO_DATE ('20/08/2023 11:25 ', 'DD/MM/YYYY HH24:MI'), 'S', '980');

COMMIT;